from environs import env

env.read_env()

EVENTBRITE_TOKEN = env("EVENTBRITE_TOKEN")
EVENTBRITE_URL = env("EVENTBRITE_URL")
DB_URL = env("DB_URL")
SECRET_KEY = env("SECRET_KEY")
REDIS_PASSWORD = env("REDIS_PASSWORD")
MINIO_ROOT_USER = env("MINIO_ROOT_USER")
MINIO_ROOT_PASSWORD = env("MINIO_ROOT_PASSWORD")