"""adding column in user table

Revision ID: 0204807a17ed
Revises: 1ae2390553e2
Create Date: 2025-08-21 18:50:50.496082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0204807a17ed'
down_revision: Union[str, Sequence[str], None] = '1ae2390553e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "username", new_column_name="email")
    op.add_column('user', sa.Column('age', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", new_column_name="username")
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
