"""deleting column from user table

Revision ID: 2cc9d60ad351
Revises: 0204807a17ed
Create Date: 2025-08-21 18:57:20.419954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2cc9d60ad351'
down_revision: Union[str, Sequence[str], None] = '0204807a17ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
