"""change chat table

Revision ID: 6aa2c52fe99a
Revises: 9b562b9c44a0
Create Date: 2025-08-27 20:41:15.500066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6aa2c52fe99a'
down_revision: Union[str, Sequence[str], None] = '9b562b9c44a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat', 'user', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'receiver_id')
    # ### end Alembic commands ###
