"""change sender_id to user_id

Revision ID: 9b562b9c44a0
Revises: 330302802914
Create Date: 2025-08-27 19:57:53.360768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b562b9c44a0'
down_revision: Union[str, Sequence[str], None] = '330302802914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chat_sender_id_fkey'), 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'user', ['user_id'], ['id'])
    op.drop_column('chat', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sender_id_fkey'), 'chat', 'user', ['sender_id'], ['id'])
    op.drop_column('chat', 'user_id')
    # ### end Alembic commands ###
