"""rename column name email

Revision ID: fca5dc5e4cc9
Revises: c09be1ca9655
Create Date: 2025-08-21 17:39:04.916223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fca5dc5e4cc9'
down_revision: Union[str, Sequence[str], None] = 'c09be1ca9655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", new_column_name="username")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # In downgrade()
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
